package template
// Do Not Edit
// Generated by Blip

import (
	"blip/blipUtil"
	"context"
	"fmt"
	"io"
)



func GameListTestProcess( c context.Context, w io.Writer ) (terror error) {
	var si = blipUtil.Instance()
	defer func() {
		if err := recover(); err != nil {
			fmt.Printf("Catch panic %s: %s\n", "GameListTestProcess", err)
			terror = fmt.Errorf("%v", err)
		}
	}()
	si.IncProcess()
	// Line: 1
	var ctxL1 = context.WithValue(c, "__Blip__", 1)
		// Line: 4
		var contentF1S1 = func() (terror error) {
			// Line: 20
			si.Write(w, []byte("\n<style>\n\n    .scroller {\n        height: 300px;\n        xbackground-color: coral;\n        overflow: scroll;\n    }\n\n    .gameEntryPanel {\n        border: 10px solid #0f5132; border-radius: 20px;\n        margin-bottom: 10px;\n    }\n\n</style>\n\n"))
			return
		}
		ctxL1 = context.WithValue(ctxL1, "styles", contentF1S1)		// Line: 23
		var contentF1S2 = func() (terror error) {
			// Line: 55
			si.Write(w, []byte("\n\n\n<div class=\"scroller\">\n\n    <!-- A Game in play -->\n    <div class=\"gameEntryPanel\">\n            <pre >\n            <b>Your Turn</b>\n            <b>Opponent Name</b> <small>(rating)</small>\n            Moves: 45\n            </pre>\n    </div>\n\n    <div class=\"gameEntryPanel\">\n            <pre >\n            <b>Your Turn</b>\n            <b>Opponent Name</b> <small>(rating)</small>\n            Moves: 45\n            </pre>\n    </div>\n\n    <div class=\"gameEntryPanel\">\n            <pre >\n            <b>Your Turn</b>\n            <b>Opponent Name</b> <small>(rating)</small>\n            Moves: 45\n            </pre>\n    </div>\n\n</div>\n\n"))
			return
		}
		ctxL1 = context.WithValue(ctxL1, "content", contentF1S2)
	terror = TestProcess(ctxL1, w)
	if terror != nil { return }
	// Line: 61
	si.Write(w, []byte("\n\n\n\n\n"))
	return
}