package template

// Do Not Edit
// Generated by Blip 0.1.3
// 2022-11-05 10:22:29.102055 -0400 EDT m=+0.000928545

import (
	"blip/blipUtil"
	"context"
	"fmt"
	"io"
)

func HeadProcess(title string, c context.Context, w io.Writer) (terror error) {
	var si = blipUtil.Instance()
	defer func() {
		if err := recover(); err != nil {
			terror = fmt.Errorf("%v", err)
		}
	}()
	si.IncProcess()
	// Line: 3
	si.Write(w, []byte("<html>\n    "))
	// Line: 3
	si.WriteStrSafe(w, title)
	// Line: 4
	si.Write(w, []byte("\n</html>"))
	return
}
