package template
// Do Not Edit
// Generated by Blip

import (
	"blip/blipUtil"
	"context"
	"fmt"
	"io"
)



func HeadProcess( title string, c context.Context, w io.Writer ) (terror error) {
	var si = blipUtil.Instance()
	defer func() {
		if err := recover(); err != nil {
			fmt.Printf("Catch panic %s: %s\n", "HeadProcess", err)
			terror = fmt.Errorf("%v", err)
		}
	}()
	si.IncProcess()
	// Line: 3
	si.Write(w, []byte("<html>\n    "))
	// Line: 3
	si.WriteStrSafe(w, title )
	// Line: 4
	si.Write(w, []byte("\n</html>"))
	return
}