package template

// Do Not Edit
// Generated by Blip 0.1.3
// 2022-11-05 10:22:29.102826 -0400 EDT m=+0.001700436

import (
	"blip/blipUtil"
	"context"
	"fmt"
	"io"
)

func TestProcess(c context.Context, w io.Writer) (terror error) {
	var si = blipUtil.Instance()
	defer func() {
		if err := recover(); err != nil {
			terror = fmt.Errorf("%v", err)
		}
	}()
	si.IncProcess()
	title := c.Value("title").(string)
	// Line: 3
	si.Write(w, []byte("<head>\n    <title>"))
	// Line: 3
	si.WriteStrSafe(w, title)
	// Line: 7
	si.Write(w, []byte("</title>\n\n</head>\n<body>\n    "))
	// Line: 7
	si.CallCtxFunc(c, "body")
	// Line: 9
	si.Write(w, []byte("\n\n    "))
	// Line: 9
	si.CallCtxFunc(c, "javascript")
	// Line: 13
	si.Write(w, []byte("\n\n    (c)Copyright 2022\n</body>\n"))
	return
}
