package template
// Do Not Edit
// Generated by Blip

import (
	"blip/blipUtil"
	"context"
	"fmt"
	"io"
)



func TestProcess( c context.Context, w io.Writer ) (terror error) {
	var si = blipUtil.Instance()
	defer func() {
		if err := recover(); err != nil {
			fmt.Printf("Catch panic %s: %s\n", "TestProcess", err)
			terror = fmt.Errorf("%v", err)
		}
	}()
	si.IncProcess()
	title := c.Value("title").(string)
	// Line: 3
	si.Write(w, []byte("<head>\n    <title>"))
	// Line: 3
	si.WriteStrSafe(w, title)
	// Line: 10
	si.Write(w, []byte("</title>\n\n</head>\n\n\n\n<body>\n    "))
	// Line: 11
	terror = si.CallCtxFunc(c, "styles")
	if terror != nil { return }
	// Line: 12
	si.Write(w, []byte("\n    "))
	// Line: 13
	terror = si.CallCtxFunc(c, "body")
	if terror != nil { return }
	// Line: 14
	si.Write(w, []byte("\n    "))
	// Line: 15
	terror = si.CallCtxFunc(c, "javascript")
	if terror != nil { return }
	// Line: 19
	si.Write(w, []byte("\n    (c)Copyright 2022\n</body>\n\n"))
	return
}