package component
// Do Not Edit
// Generated by Blip
// source blip: ./html/component/userDetail.blip.html

import (
	"context"
	"fmt"
	"github.com/samlotti/blip/blipUtil"
	"github.com/samlotti/blip/examples/template/blipWebServer/model"
	"io"
	"time"
	html "github.com/samlotti/blip/blipped/html"
)



func UserDetailRender( user *model.User, c context.Context, w io.Writer ) (terror error) {
    start := time.Now()

	var si = blipUtil.Instance()
	var escaper = si.GetEscaperFor( "html") 
	defer func() {
		if err := recover(); err != nil {
			fmt.Printf("Catch panic %s: %s\n", "UserDetailRender", err)
			terror = fmt.Errorf("%v", err)
		}
	    si.RenderComplete(escaper, "userDetail", "html", time.Since(start), terror)
	}()
	// Line: 3
	si.Write(w, []byte("\n\n"))
	// Line: 7
	si.Write(w, []byte("\n"))
	// Line: 9
	var ctxL1 = context.WithValue(c, "__Blip__", 1)
		// Line: 11
		var contentF1S1 = func() (terror error) {
			// Line: 13
			si.Write(w, []byte("<style>\n</style>\n"))
			// End of content block
			return
		}
		ctxL1 = context.WithValue(ctxL1, "styles", contentF1S1)		// Line: 16
		var contentF1S2 = func() (terror error) {
			// Line: 20
			si.Write(w, []byte("\n<div class=\"container\">\n\n    <div class=\"page-header\">\n        <h1>"))
			// Line: 20
			si.WriteStrSafe(w, user.Name , escaper)
			// Line: 23
			si.Write(w, []byte("</h1>\n    </div>\n\n    <label>"))
			// Line: 23
			si.WriteStrSafe(w, user.Title, escaper)
			// Line: 24
			si.Write(w, []byte("</label>\n    <label>"))
			// Line: 24
			si.WriteStrSafe(w, user.EMail, escaper)
			// Line: 27
			si.Write(w, []byte("</label>\n\n    <div class=\"card\" style=\"width: 18rem;\">\n        <img class=\"card-img-top\" src=\""))
			// Line: 27
			si.WriteStr(w, user.Profile)
			// Line: 30
			si.Write(w, []byte("\" alt=\"Card image cap\">\n        <small>Images generated by <a href=\"https://generated.photos/\" target=\"gf\">Generated Photos</a></small>\n        <div class=\"card-body\">\n            <h5 class=\"card-title\">"))
			// Line: 30
			si.WriteStrSafe(w, user.Title, escaper)
			// Line: 31
			si.Write(w, []byte("</h5>\n            <a href=\"#\" class=\"xbtn xbtn-primary\">"))
			// Line: 31
			si.WriteStrSafe(w, user.EMail, escaper)
			// Line: 33
			si.Write(w, []byte("</a>\n\n            "))
			// Line: 34
			if user.Active {
				// Line: 35
				si.Write(w, []byte("            <div class=\"alert alert-success\" role=\"alert\">Active</div>\n            "))
				// Line: 36
			} else {
				// Line: 37
				si.Write(w, []byte("\n            <div class=\"alert alert-danger\" role=\"alert\">This user is inactive.</div>\n            "))
				// Line: 38
			}
			// Line: 45
			si.Write(w, []byte("\n        </div>\n    </div>\n\n</div>\n\n\n\n"))
			// End of content block
			return
		}
		ctxL1 = context.WithValue(ctxL1, "mainContent", contentF1S2)
	terror = html.RootRender(user.Name, ctxL1, w)
	if terror != nil { return }
	// Line: 47
	si.Write(w, []byte("\n"))
	return
}