package component
// Do Not Edit
// Generated by Blip

import (
	"blip/blipUtil"
	"blip/examples/template/blipWebServer/html"
	"blip/examples/template/blipWebServer/model"
	"context"
	"fmt"
	"io"
	"time"
)



func UserDetailProcess( user *model.User, c context.Context, w io.Writer ) (terror error) {
    start := time.Now()

	var si = blipUtil.Instance()
	var escaper = si.GetEscaperFor( "html") 
	defer func() {
		if err := recover(); err != nil {
			fmt.Printf("Catch panic %s: %s\n", "UserDetailProcess", err)
			terror = fmt.Errorf("%v", err)
		}
	    si.RenderComplete(escaper, "userDetail", "html", time.Since(start), terror)
	}()
	// Line: 2
	si.Write(w, []byte("\n"))
	// Line: 6
	si.Write(w, []byte("\n"))
	// Line: 8
	var ctxL1 = context.WithValue(c, "__Blip__", 1)
		// Line: 10
		var contentF1S1 = func() (terror error) {
			// Line: 12
			si.Write(w, []byte("<style>\n</style>\n"))
			// End of content block
			return
		}
		ctxL1 = context.WithValue(ctxL1, "styles", contentF1S1)		// Line: 15
		var contentF1S2 = func() (terror error) {
			// Line: 19
			si.Write(w, []byte("\n<div class=\"jumbotron\">\n\n    <div class=\"page-header\">\n        <h1>"))
			// Line: 19
			si.WriteStrSafe(w, user.Name , escaper)
			// Line: 19
			si.Write(w, []byte("<small>"))
			// Line: 19
			si.WriteStrSafe(w, user.Title, escaper)
			// Line: 22
			si.Write(w, []byte("</small></h1>\n    </div>\n\n    "))
			// Line: 23
			if user.Active {
				// Line: 24
				si.Write(w, []byte("    <div class=\"alert alert-success\" role=\"alert\">Active user</div>\n    "))
				// Line: 25
			} else {
				// Line: 26
				si.Write(w, []byte("\n    <div class=\"alert alert-danger\" role=\"alert\">This user is inactive.</div>\n    "))
				// Line: 27
			}
			// Line: 32
			si.Write(w, []byte("\n\n</div>\n\n\n\n"))
			// End of content block
			return
		}
		ctxL1 = context.WithValue(ctxL1, "mainContent", contentF1S2)
	terror = html.RootProcess(user.Name, ctxL1, w)
	if terror != nil { return }
	// Line: 34
	si.Write(w, []byte("\n"))
	return
}