package template
// Do Not Edit
// Generated by Blip
// source blip: examples/template/head.blip

import (
	"context"
	"fmt"
	"github.com/samlotti/blip/blipUtil"
	"io"
	"time"
)



func HeadRender( title string, c context.Context, w io.Writer ) (terror error) {
    start := time.Now()

	var si = blipUtil.Instance()
	var escaper = si.GetEscaperFor( "text") 
	defer func() {
		if err := recover(); err != nil {
			fmt.Printf("Catch panic %s: %s\n", "HeadRender", err)
			terror = fmt.Errorf("%v", err)
		}
	    si.RenderComplete(escaper, "head", "text", time.Since(start), terror)
	}()
	// Line: 3
	si.Write(w, []byte("<html>\n    "))
	// Line: 3
	si.WriteStrSafe(w, title , escaper)
	// Line: 4
	si.Write(w, []byte("\n</html>"))
	return
}