package users

// Do Not Edit
// Generated by Blip 0.1.3
// 2022-11-05 10:22:29.103781 -0400 EDT m=+0.002655180

import (
	"blip/blipUtil"
	"blip/template"
	"context"
	"fmt"
	"io"
	"strings"
)

// Function block from line: 15
func toUpper(str string) string {
	return strings.ToUpper(str)
}

func ListUsersProcess(name string, c context.Context, w io.Writer) (terror error) {
	var si = blipUtil.Instance()
	defer func() {
		if err := recover(); err != nil {
			terror = fmt.Errorf("%v", err)
		}
	}()
	si.IncProcess()
	// Line: 3
	si.Write(w, []byte("\n"))
	// Line: 6
	si.Write(w, []byte("\n\n"))
	// Line: 7

	terror = template.HeadProcess("User Page", c, w)
	if terror != nil {
		return
	}
	// Line: 8
	si.Write(w, []byte("\nHi "))
	// Line: 8
	si.WriteStrSafe(w, name)
	// Line: 9
	si.Write(w, []byte("\n"))
	// Line: 9
	var ctxL1 = context.WithValue(c, "__Blip__", 1)
	// Line: 9
	var contentF1 = func() {
		// Line: 9
		si.Write(w, []byte("The list of all users"))
	}
	ctxL1 = context.WithValue(ctxL1, "body", contentF1)
	terror = template.TestProcess(ctxL1, w)
	if terror != nil {
		return
	}
	// Line: 11
	si.Write(w, []byte("\nThe end of the line\n"))
	return
}
